### ISSUE TITLE
[FEATURE] P0 Nested Function Support

### ISSUE THREAD

**Issue by forestmvey** [opensearch-project/sql#1111]
**Is your feature request related to a problem?**
The `nested` query is supported in the legacy engine and not the V2 engine. As Legacy engine is becoming deprecated we need to support this functionality in the V2 engine.

Example:
```
SELECT nested(message.info) FROM nested_objects;
SELECT * FROM nested_objects WHERE nested(message.info)='b';
SELECT nested(message.info) FROM nested_objects ORDER BY nested(message.info);
SELECT nested(message.*) FROM nested_objects;
```

**What solution would you like?**
Port over functionality for the `nested` query to the V2 engine with the same functionality as in Legacy.

Release-Schedule
- P\[0\] ~~`SELECT` clause support~~
  - P\[0\] ~~DOT notation field support~~ - Released: [1490](https://github.com/opensearch-project/sql/pull/1490)
  - P\[0\] ~~`*` support as inner field, Example: `nestedField.innerFields.*`~~ - Released: [1773](https://github.com/opensearch-project/sql/pull/1773)
- P\[0\] ~~`WHERE` clause support; one syntax will be prioritized.~~
  - P\[0\] ~~Syntax: `nested(field | field, path) OPERATOR LITERAL`~~ - Released: [1657](https://github.com/opensearch-project/sql/pull/1657)
- P\[0\] ~~`ORDER BY` clause support~~ - Released: [1789](https://github.com/opensearch-project/sql/pull/1789)

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
N/A

**Comment by forestmvey** [comment]
Demo video for nested function use in SELECT clause.

https://user-images.githubusercontent.com/36905077/234379257-b368a890-64f7-42fb-afc3-deef113892fb.mp4

**Comment by GumpacG** [comment]
Hi @dai-chen and @penghuo, `nested(field.*)` needs to be supported and some grammar changes are required. Below are options that were most reasonable out of many that were explored.

A new rule is proposed in order to add a new node that is similar to `AllFields` and will be used in `SymbolTable` to find all fields with the same path as the argument (e.g. field.* will include field.subfield1, field.subfield2,...). The proposed rule is to have an `allTupleFields` which can be used for both `object` and `nested` types when we begin to support `SELECT field.*`.
```
allTupleFields
    : ident DOT STAR
    ;
```

### Options for grammar changes:
1. `allTupleFields` in `expressionAtom`
2. `allTupleFields` in `functionCall`
3. `allTupleFields` in `functionArg`


### Option details:
<table>
<tr>
<td><b>Grammar changes</td>
<td><b>Pros</td>
<td><b>Cons</td>
</tr>

<tr>
<td>1. allTupleFields in expressionAtom
<pre>
expressionAtom
     : allTupleFields             #allTupleFieldsExpressionAtom
</pre>
</td>
<td>
<ul>
<li> adds support for partiQL syntax</li>
<li>less/no refactoring when adding support for partiQL and is used in the following clauses:</li>
<ul>
<li>SELECT</li>
<li>WHERE</li>
<li>GROUP BY</li>
<li>ORDER BY</li>
<li>HAVING</li>
</ul>
<li>FROM clause is not affected</li>

<li>Supports:</li>
<ul>
<li>SELECT message.* FROM nested</li>

<li>SELECT nested(message.*) FROM nested</li>
</ul>
</td>
<td>May introduce errors or worse, invalid results like:
<pre>
opensearchsql> SELECT * FROM nested_table GROUP BY message.*;
fetched rows / total rows = 0/0
+---------------------+----------------+------------------+
| message.dayOfWeek   | message.info   | message.author   |
|---------------------+----------------+------------------|
+---------------------+----------------+------------------+
opensearchsql> SELECT * FROM nested_table GROUP BY myNum.*;
fetched rows / total rows = 0/0
</pre></td>
</tr>

<tr>
<td>2. Specific case only for nestedAllFunctionCall in functionCall
<pre>
functionCall
    : nestedFunctionName LR_BRACKET allTupleFields RR_BRACKET      #nestedAllFunctionCall
</pre>
</td>
<td>
<ul>
<li>Isolated implementation for star within nested function which shouldn’t affect other functions</li>

<li>Supports <pre>SELECT nested(message.*) FROM nested</pre></li></ul></td>
<td><ul>
<li>Doesn’t support PartiQL which may lead to some refactoring when implementing PartiQL support.</li></td>
</tr>

<tr>
<td>3. allTupleFields in functionArg
<pre>
functionArg
    : expression
    | allTupleFields
</pre>
</td>
<td>
<ul>
<li>Only affects functions</li>

<li>Supports <pre>SELECT nested(message.*) FROM nested</pre></li></ul></td>
<td>
<ul>
<li>May introduce errors based on user errors for queries like

<pre>SELECT abs(int0.*) FROM calcs</pre></td>
</tr>

</table>

### Additional Context:
**Option 1:**
This change has the same effect as adding `allTupleFields` to `columnName` as it is only used in the `expressionAtom`. PartiQL implementation can be started in order for this option to reduce the risks. Implementing PartiQL could take a great amount of effort as it depends on updating indexScans to support table aliases.

**Option 2:**
This option seems the safest in the meantime while PartiQL support is yet to start. Value is added in the short term while refactoring if needed in the future is minimal. This may not need to be refactor, if it does then it is just a matter of removing it from the grammar.

**Option 3:**
This option has the risk of option 1 without its benefits of avoiding PartiQL refactoring in the future.

**Comment by GumpacG** [comment]
Discussed offline and agreed on option 2.
cc: @penghuo, @dai-chen

**Comment by acarbonetto** [comment]
Phase 2 support: https://github.com/opensearch-project/sql/issues/1806
