### ISSUE TITLE
Observability - PPL Visualization support

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/sql#162]
**Is your feature request related to a problem? Please describe.**
Make PPL support visualization

**Additional context**
Response
- Labels (x-axis)
- Values (y-axis)
- Meta data
- Other related data

**Comment by chloe-zh** [comment]
Proposal:

Data format
```
{
  "data": {
    field_a: [a1, a2, a3], // unsorted
    field_b: [b1, b2, b3],  // unsorted, align with field_a
    field_c: [c1, c2, c3],  // unsorted, align with field_a
    field_d: [d1, d2, d3],  // unsorted, align with field_a
    ...
  },
  "metadata": {
    "x": {
      "fieldname": "field_a",
      "alias": "a"
      "type": "text"
    },
    "y": {
      "fieldname":"field_b",
      "alias": "b",
      "type": "double"
    },
    "other_groups": [
      {
        "fieldname": "field_c",
        "alias": "c",
        "type": "text"
      },
      {
        "fieldname": "field_d",
        "alias": "d",
        "type": "integer"
      },
    ]
  },
  "size": 3
  "status": 200
}
```

**Comment by chloe-zh** [comment]
Proposal in response format:

Example: source = my_index | stats avg(some_field) as field_b by field_a, field_c, field_d
(field_a is set as x by default here since the new grammar and functionality is not supported yet, for poc only)
```
{
  "data": [
    {
      "field_a": [a1, a2, a3],
      "field_b": [b1, b2, b3],
      "field_c": c1,
      "field_d": d1,
    },
    {
      "field_a": [a4, a5, a6, a7],
      "field_b": [b4, b5, b6, b7]
      "field_c": c2,
      "field_d": d2,
    },
    {
      "field_a": [a8, a9],
      "field_b": [b8, b9],
      "field_c": c3,
      "field_d": d3
    }
  ],
  "metadata": {
    "x": {
      "fieldname": "field_a",
      "type": "text"
    },
    "y": {
      "fieldname":"field_b",
      "type": "double"
    },
    "other_groups": [
      {
        "fieldname": "field_c",
        "type": "text"
      },
      {
        "fieldname": "field_d",
        "type": "integer"
      },
    ]
  },
  "size": 9
  "status": 200
}
```

After simple processing by frontend the data value arrays will look like:
```
var trace1 = {
  x: [a1, a2, a3],
  y: [b1, b2, b3],
  type: 'bar',
  name: 'y-x value with c=c1 d=d1',
  ...
};

var trace2 = {
  x: [a4, a5, a6, a7],
  y: [b4, b5, b6, b7],
  type: 'bar'
  name: 'y-x value with c=c2, d=d2'
};

var trace3 = {
  x: [a8, a9],
  y: [b8, b9],
  type: 'bar',
  name: 'y-x value with c=c3, d=d3'
};
```


Error format is the same with JDBC error:
```
{
  "error": {
    "reason": "some error reason",
    "details": "some details",
    "type": "exception type"
  },
  "status": 404/503/...
}
```

**Comment by chloe-zh** [comment]
Contd:

Another example: `source = people | stats count() as my_count by city`
```
{
  "data": [
    {
      "city": ["Seattle", "Palo Alto", "Los Angelos", "Portland"],
      "my_count": [10, 12, 7, 3]
    },
    "metadata": {
      "x": {
        "name": "my_count",
        "type": "integer"
      },
      "y": {
        "name": "city",
        "type": "text"
      }
    },
    "size": 4,
    "status": 200
  ]
}
```

**Comment by chloe-zh** [comment]
In PoC phase, the data format is requested with endpoint of `?format=viz`

**Comment by chloe-zh** [comment]
This thread notes down some concerns and issues

**Comment by chloe-zh** [comment]
The proposed response format above is for the convenience of the frontend, but here are still some issues and concerns:

We can see the data part in the response format, for each element in the data array, the x field and y field values are grouped by the other fields, for example:

```
"data": [
  {
    "count()": [1, 3, 2, 5],
    "age": [23, 26, 31, 33]
    "gender": "F"
  },
  {
    "count()": [2, 3. 4, 5],
    "age": [23, 24, 31, 26]
    "gender": "M"
  }
],
"metadata"
{
  "x": {
    "name": "age",
    ...
  },
  "y‘: {
    "name": "count()"
  },
 "other": [...]
}
```

In this example, the result has 3 fields. For every unique "gender" field, the response should give the data columns for (age, count) tuple. This is do-able if there are not many fields, like 2, 3 or even 4. But this becomes not meaningful when there are too many fields both for backend implementation and frontend use.

**Comment by chloe-zh** [comment]
Proposal of the span grammar in `stats` command:
`... | stats agg_function(field_expr) by span(timeseries_field, interval_str)`

Example 1: 
`source=opensearch_dashboards_sample_data_flights | stats count() by span(timestamp, '4h')`  
=> count the total of flights by every 4 hours 
Result:
```
{
  "data": {
    "count()": [
      53,
      55,
      64,
      63,
      57,
      ...
    ],
    "Span(field\u003dField(field\u003dtimestamp, fieldArgs\u003d[]), span\u003d4h)": [
      "2021-07-12 00:00:00",
      "2021-07-12 04:00:00",
      "2021-07-12 08:00:00",
      "2021-07-12 12:00:00",
      "2021-07-12 16:00:00",
      ...
    ]
  },
  "metadata": {
    "xfield": {
      "name": """Span(field=Field(field=timestamp, fieldArgs=[]), span=4h)""",
      "type": "timestamp"
    },
    "yfield": {
      "name": "count()",
      "type": "integer"
    },
    "fields": [
      {
        "name": "count()",
        "type": "integer"
      },
      {
        "name": """Span(field=Field(field=timestamp, fieldArgs=[]), span=4h)""",
        "type": "timestamp"
      }
    ]
  },
  "size": 252,
  "status": 200
}
```

Example 2: 
`source=opensearch_dashboards_sample_data_ecommerce | stats avg(taxful_total_price) by span(order_date, '3d')`
=> calcuate the average taxful total prices of the products by every 3 calendar days of the order date
Result:
```
{
  "data": {
    "avg(taxful_total_price)": [
      70.83713942307692,
      76.0724537700688,
      77.10022078804347,
      71.9179058908046,
      77.7894653867713,
      ...
    ],
    "Span(field\u003dField(field\u003dorder_date, fieldArgs\u003d[]), span\u003d3d)": [
      "2021-07-08 00:00:00",
      "2021-07-11 00:00:00",
      "2021-07-14 00:00:00",
      "2021-07-17 00:00:00",
      "2021-07-20 00:00:00",
      ...
    ]
  },
  "metadata": {
    "xfield": {
      "name": """Span(field=Field(field=order_date, fieldArgs=[]), span=3d)""",
      "type": "timestamp"
    },
    "yfield": {
      "name": "avg(taxful_total_price)",
      "type": "double"
    },
    "fields": [
      {
        "name": "avg(taxful_total_price)",
        "type": "double"
      },
      {
        "name": """Span(field=Field(field=order_date, fieldArgs=[]), span=3d)""",
        "type": "timestamp"
      }
    ]
  },
  "size": 11,
  "status": 200
}
```

**Comment by chloe-zh** [comment]
The span clause in stats command only allows time span in PoC phase. The PoC code changes are in this branch: https://github.com/chloe-zh/opensearch-sql/tree/observability/poc/ppl-stats

**Comment by chloe-zh** [comment]
Hi @mengweieric 

[opensearch-sql-poc.zip](https://github.com/opensearch-project/sql/files/6873375/opensearch-sql-1.0.0.0.zip)

Here is the artifact for the visualization PoC use. The attached version has mainly 2 major changes compared to our stable released version:
1. The poc version has a new response format for the visualization use, to get use of this format, you will need to attach a param `format=viz` at the end of the request endpoint (example: `localhost:9200/_plugins/_ppl?format=viz`). This format constructs the result data in column arrays rather than in rows like JDBC format. It also returns the column names and data types as meta data. Besides, it defines the “x field” and “y field” for you to create the 2-dimensional visualizations, but it did not define the x, y fields when the result contains 3 or more fields in this poc artifact, since the requirements for multi-field visualization is not clear yet.
2. This version also provides a span functionality in the PPL stats command, so that you can achieve the time series demo with PPL now. But actually I didn’t implement it in the physical operators of the query engine yet but push the span directly to the opensearch engine, so you might find not able to do some super complex search, but it works fine with basic searches.

For more details and examples, please see the comments above.

**Comment by dai-chen** [comment]
Closing. Please open separate issue if anything else. Thanks!
