### ISSUE TITLE
[FEATURE] Support flexible grouping order in aggregation including span

### ISSUE THREAD

**Issue by xinyual** [opensearch-project/sql#2719]
**Is your feature request related to a problem?**
When query using PPL, we find 
`source=opensearch_dashboards_sample_data_logs |stats COUNT() as cnt by span(timestamp, 1d), response` could work but `source=opensearch_dashboards_sample_data_logs |stats COUNT() as cnt by response， span(timestamp, 1d)` fails. It is unreasonable because the order should not influence the execution result. It works well if `span` is not included

**What solution would you like?**
Support flexible order when including   `span`

**Comment by LantaoJin** [comment]
Span will always be the first grouping expression in grouping list in current implementation.
Microsoft Kusto Query Language (KQL) has similar behavior (You can try [here] (https://dataexplorer.azure.com/clusters/help/databases/Samples)) with below quoted statements.
>StormEvents 
| summarize avg(DamageProperty) by bin(StartTime, 1d), State, EventType

and
>StormEvents 
| summarize avg(DamageProperty) by State, EventType, bin(StartTime, 1d)

both use `StartTime` bin as the first grouping key in results. But all queries could be executed.

PPL query
``` 
source=opensearch_dashboards_sample_data_logs | stats COUNT() as cnt by response, span(timestamp, 1d)
```
fails with `SyntaxCheckException` that seems not make sense.

**Comment by LantaoJin** [comment]
The [stats syntax](https://opensearch.org/docs/latest/search-plugins/sql/ppl/functions/#syntax-6) in our official document doesn‘t state that `span` must be the first expression of `by-clause`. But its order is declared in `stats.rst` as a design from https://github.com/opensearch-project/sql/pull/417. https://github.com/opensearch-project/sql/blob/3ab785179db593a3999efffb347d897ea8364853/docs/user/ppl/cmd/stats.rst?plain=1#L42
Based on current implementation, `span` is a [dedicated member](https://github.com/opensearch-project/sql/blob/3ab785179db593a3999efffb347d897ea8364853/core/src/main/java/org/opensearch/sql/ast/tree/Aggregation.java#L50) of `Aggregation`(UnresolvedPlan), rather than a part of `groupExprList`. The `span` member variable will be filled into the first grouping key when converting to `LogicalAggregation`.
Should we support this enhancement? Any thoughts @penghuo ?

**Comment by dblock** [comment]
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]
