### ISSUE TITLE
Unable to escape characters for string literals[BUG]

### ISSUE THREAD

**Issue by ghost** [opensearch-project/sql#297]
**Describe the bug**
Unable to escape characters for string literals

Or for query issues:
1. Run the query `SELECT 'i\'m'`
2. See unexpected result `i\'m`

**Expected behavior**
The result should be `i'm`

**Screenshots**
![image](https://user-images.githubusercontent.com/90278068/142924788-b8a32556-2037-45be-8aa2-3cecbefc8e18.png)

**Comment by guiangumpac** [comment]
This issue affects TDVT tests:
- exprtests/standard\setup.logical.txt

**Comment by Yury-Fridlyand** [comment]
Adding more info to this bug:
* PPL and SQL both affected
* character escaping rules are not applied to all string literals

Some examples:
```sql
SELECT 'Pat O''Hanrahan & <Matthew Eldridge]'''
```
returns
`Pat O''Hanrahan & <Matthew Eldridge]''` instead of `Pat O'Hanrahan & <Matthew Eldridge]'`
```sql
SELECT * FROM staples WHERE `Customer Name` = "Mary O'Rourke";
```
returns valid result, but
```sql
SELECT * FROM staples WHERE `Customer Name` = 'Mary O\'Rourke';
```
yields empty result set.
In case of `PPL`
```sql
source=staples | WHERE `Customer Name` = "Mary O'Rourke";
```
returns valid data, but
```sql
source=staples | WHERE `Customer Name` = 'Mary O\'Rourke';
```
doesn't.

`staples` table is a [sample data from TDVT suite](https://github.com/tableau/connector-plugin-sdk/tree/master/tests/datasets/TestV1).

**Comment by MaxKsyunz** [comment]
Adding the following test to `sql/src/test/java/org/opensearch/sql/sql/parser/AstExpressionBuilderTest.java` will also reproduce the problem.

```java
 @Test
  public void canBuildEscapedStringLiteral() {
    assertEquals(
            stringLiteral("O'Rourke"),
            buildExprAst("'O\\'Rourke'")
    );
  }
```

**Comment by dai-chen** [comment]
Tested and I think this is already fixed in https://github.com/opensearch-project/sql/pull/696:

```
POST _plugins/_sql
{
  "query": """
    SELECT 'O\'Rourke'
  """
}
{
  "schema": [
    {
      "name": """'O\'Rourke'""",
      "type": "keyword"
    }
  ],
  "datarows": [
    [
      """O\'Rourke"""
    ]
  ],
  "total": 1,
  "size": 1,
  "status": 200
}
```

**Comment by Yury-Fridlyand** [comment]
Fix for escape characters is coming in https://github.com/Bit-Quill/opensearch-project-sql/pull/159. It is a breaking change, so it is targeted to 3.x branch.
