### ISSUE TITLE
[FEATURE]PPL new `trendline` command

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/sql#3013]
**Is your feature request related to a problem?**

Adding a new PPL `trendline` command to support computing a moving averages of fields.

We would like to support two flavours of moving average:

 ****SMA** : Simple moving average**

- f[i]: The value of field 'f' in the i-th data-point
- n: The number of data-points in the moving window (period)
- t: The current time index

`SMA(t) = (1/n) * Σ(f[i]), where i = t-n+1 to t`

---

****WMA** :  Weighted moving average**

`WMA(t) = Σ(w[i] * f[i]) / Σ(w[i]), where i = t-n+1 to t`
Where w[i] is the weight for the i-th data-point. 

In a typical WMA, the weights are linearly decreasing from the most recent to the oldest data-point:
`w[i] = n - (t - i), where i = t-n+1 to t`

The complete forumlation would be:
`WMA(t) = Σ((n - (t - i)) * f[i]) / Σ(n - (t - i)), where i = t-n+1 to t`

---

**Example**

The next command shows a trendline over a 5 month period events by month
```sql
source=t | stats count(date_month) | trendline sma(5, count) AS trend | fields  trend
```
The next command would compute a 5-point simple moving average of the 'cpu_usage' field and store it in a new field called 'smooth_cpu'.
```sql
source=t| trendline sma(5,cpu_usage) as smooth_cpu
```

Multiple trendlines could be calculated in a single command, such as 
```sql
| trendline sma(10,memory) as mem_trend wma(5,network_traffic) as net_trend.
```

**Comment by jduo** [comment]
Cross-posting from the PPL PR:

I have this almost hooked up. I loaded the students table which has name, gpa, and grad_year fields. When I issue this PPL query, it seems like it is using the schema from the implied ProjectOperator instead of using the schema from the TRENDLINE command, even though I overrode TrendlineOperator#schema() to just build a schema based on the computations list: { "query" : "source=students | TRENDLINE SMA(1, gpa) as foo " } 

I get the following JSON result of null arrays:  { "schema": [ { "name": "grad_year", "type": "long" }, { "name": "name", "type": "string" }, { "name": "gpa", "type": "float" } ], "datarows": [ [ null, null, null ], [ null, null, null ], [ null, null, null ] ], "total": 3, "size": 3 }

However if change the PPL to use an alias that happens to have the same name as the original field: { "query" : "source=students | TRENDLINE SMA(1, gpa) as gpa " }  I get data back correctly for one of the array elements in each row.

Is it correct that ProjectOperator does not use the schema from its input?

I would expect the only field out of this schema to be the one computation in trendline ("foo"), rather than all 3 fields in the real index, but perhaps I'm mistaken here.

I also noticed that the PhysicalPlan class mentions that only ProjectOperator should implement schema():
https://github.com/opensearch-project/sql/blob/7666a44b7e07bd673bdd35d94a33f87cd98e3905/core/src/main/java/org/opensearch/sql/planner/physical/PhysicalPlan.java#L43

Is the proper way to specify a schema for an operator to implement the operator then create a ProjectOperator on top of it?

Thanks

**Comment by jduo** [comment]
Testing Splunk's trendline command, they have the behavior where:
1. If the field in the input is not in the trendline computations, it shows up unaltered.
2. If the field is used in trendline and the computation alias is the same as the field name, it gets replaced with the trendline computation.
3. If the field is used in trendline and the computation alias has a different name than the field name, it shows up as a new field in the result.
