### ISSUE TITLE
[BUG] JDBC Driver doesn't return TIMESTAMP fractional seconds

### ISSUE THREAD

**Issue by kylepbit** [opensearch-project/sql#924]
**What is the bug?**
Timestamps with fractional seconds have the fractions stripped through the JDBC driver.

**How can one reproduce the bug?**
1. Load data into a timestamp index with fractional seconds
2. Connect using the JDBC driver
3. Issue a SELECT * query on the table
4. Notice no fractional seconds for any values

**What is the expected behavior?**
Fractional seconds match the inserted values

**What is your host/environment?**
 - OS: macOS
 - Version JDBC 1.1.0.1
 - Plugins

**Comment by Yury-Fridlyand** [comment]
Test data:
[test_data.zip](https://github.com/opensearch-project/sql/files/9805124/test_data.zip)

**Comment by MaxKsyunz** [comment]
The problem is [here](https://github.com/opensearch-project/sql/blob/b30d1567367f0de1c7f17f6930513b91050623a0/opensearch/src/main/java/org/opensearch/sql/opensearch/data/value/OpenSearchExprValueFactory.java#L182).
<img width="801" alt="image" src="https://user-images.githubusercontent.com/99687200/196308785-3754efa2-78c5-4aaf-a704-3506b08a36eb.png">

[This](https://github.com/opensearch-project/sql/blob/b30d1567367f0de1c7f17f6930513b91050623a0/core/src/main/java/org/opensearch/sql/utils/DateTimeFormatters.java#L98) is the definition of `DATE_TIME_FORMATTER`
<img width="513" alt="image" src="https://user-images.githubusercontent.com/99687200/196308837-4affa264-bf6e-4950-b9b7-9e226124ea0b.png">

The correct solution should use the formatter from specified in the mapping for the field or whatever is set as the default formatter for the cluster.

**Comment by kylepbit** [comment]
I believe this was actually a red herring - it appears to have invoked the v1 SQLEngine which doesn't have timestamp, and thus couldn't return the precision. It's now working correctly after some other changes.
